version: "3.7"

networks:
    ha-network:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/29

services:
    mqtt:
        image: toke/mosquitto
        restart: unless-stopped
        environment:
            - "TZ=Europe/Warsaw"
        ports:
            - "81:1883"
        networks:
            ha-network:
                ipv4_address: 172.28.0.2
        volumes:
            - /opt/storage/ha/mqtt/config:/mqtt/config:ro
            - /opt/storage/ha/mqtt/data:/mqtt/data
            - /opt/storage/ha/mqtt/log:/mqtt/log


    zigbee2mqtt:
        image: koenkk/zigbee2mqtt
        restart: unless-stopped
        privileged: true
        devices:
            - "/dev/ttyACM0:/dev/ttyACM0"
        networks:
            ha-network:
                ipv4_address: 172.28.0.3
        depends_on:
            - "mqtt"
        volumes:
            - /opt/storage/ha/zigbee2mqtt/data:/app/data
            - /run/udev:/run/udev:ro

    home-assistant:
        image: homeassistant/home-assistant:stable
        restart: unless-stopped
        init: true
        environment:
            - "TZ=Europe/Warsaw"
        ports:
            - "82:8123"
        networks:
            ha-network:
                ipv4_address: 172.28.0.4
        depends_on:
            - "mqtt"
            - "zigbee2mqtt"
        volumes:
            - /opt/storage/ha/homeassistant/config:/config

